Feature/multiple animations
BredaUniversityGames/Y2024-25-PR-BB pull request #119
Opened 2024-12-19 13:02 UTC by MuskettaMan

### Description

Adds functionality for improved loading of skeletal meshes, now works with more kinds of gltfs.
Adds a gun and arms models onto the camera, with animations.
Adds support for multiple animation clips.
Adds support for wren bindings into the animations system.
Adds a small demo 

### Issues

- https://bubonic-brotherhood.codecks.io/card/1ei-wren-skeleton-animation-bindings
- https://bubonic-brotherhood.codecks.io/card/1e4-interacting-with-skeletal-animation-system

### Test criteria

- [ ] Make sure the gun animations work
- [ ] Test the input controls, currently this is 'R' key for reload, and LMB for shooting
- [ ] Review the interface that is exposed to wren, does it look usable or is missing something
- [ ] Review how I expose my bindings in the binding module, perhaps this can be split up better, or use different technique for exposing them. Because right now Im doing it through funcExt, since its a wren component

2024-12-19 14:09 UTC, santiberna reviewed
In general I think you did the wren bindings well, in terms of components it is a bit unavoidable to not use external functions because of the WrenComponent<T> template. If you feel like it, I would also like it if you split the math wren bindings to another file, to keep it tidy like Leo did with the audio module. 

Besides, I have some small notes in the PR, check below

2025-01-06 09:14 UTC, dumitrurares14 commented
I see Santiago reviewed the wren stuff. As for the animation I couldn't find anything to pick on. The implementation and how they are laid out is elegant. Nice stuff 👍, I assume Santiago will approve after the separation of the math thing

2025-01-06 09:40 UTC, santiberna requested changes
Addind on my previous review of moving the math wren bindings to another file, I think you should also move some of the animation logic to its .cpp instead of header. The linter also caught some missing include errors

2025-01-06 09:40 UTC, santiberna commented on engine/renderer/public/animation.hpp
> +        auto it = std::find_if(animations.begin(), animations.end(), [&name](const auto& anim)
Forgor to include algorithm

2025-01-06 09:40 UTC, santiberna commented on engine/renderer/public/animation.hpp
> +        activeAnimation = animationIndex;
Probably move all these function definitions to a cpp file

2025-01-06 09:40 UTC, santiberna commented on engine/renderer/public/components/animation_channel_component.hpp
> +    std::unordered_map<uint32_t, TransformAnimationSpline> animationSplines;
Forgor to include unordered_map

2025-01-06 11:41 UTC, santiberna approved these changes
Looks good on wren side. Approved!

2025-01-06 11:41 UTC, santiberna commented on engine/renderer/private/animation.cpp
> +std::optional<uint32_t> AnimationControlComponent::CurrentAnimationIndex()
Simply return the optional, no need  to check if it has a value

2025-01-06 11:59 UTC, merged