Feature/serialization
BredaUniversityGames/Y2024-25-PR-BB pull request #46
Opened 2024-10-10 08:21 UTC by luuk234

[ADDED} scene serialization
[ADDED] save button
[ADDED] entity serialization interface

2024-10-10 11:06 UTC, MuskettaMan requested changes

2024-10-10 11:39 UTC, santiberna requested changes
I think you could move the Entity Serializer into another (header probably) file, but otherwise I think the question of saving with cereal or filepath is not really important unless we run into limitations

2024-10-15 08:12 UTC, MuskettaMan approved these changes
Looks good, approved, left some minor feedback on cleaning up the source files

2024-10-16 07:39 UTC, santiberna approved these changes
Okay looks a lot better. You can merge!

2024-10-16 07:44 UTC, merged