UI Module
BredaUniversityGames/Y2024-25-PR-BB pull request #87
Opened 2024-11-28 14:39 UTC by VengarvdWal

UI Rendering branch that been refactored to use the new render systems. Font rendering is now also fixed. 

This also changes how each pass should have a output for the Framegraph. 

Currently the tonemapping pass outputs an image that is blitted onto the ui target, which does it's rendering, and then outputs a uiTarget and this is blitted to the swapchain on which the debug pass draws. 

Closes these decks
https://bubonic-brotherhood.codecks.io/decks/38-ui/card/1cv-refactor-ui-branch
https://bubonic-brotherhood.codecks.io/decks/38-ui/card/18x-ui-system
https://bubonic-brotherhood.codecks.io/milestones/run/40/card/1cq-ui-text-rendering
https://bubonic-brotherhood.codecks.io/milestones/run/40/card/18g-frame-graph-nodes-are-sometimes-in-the-incorrect-order

- [x] The render output should stay the same as before
- [x] In RenderDoc the passes are now correctly sorted 
- [x] Text is rendered
- [x] Buttons are rendered

2024-12-02 15:20 UTC, MuskettaMan requested changes
Good change to the new module system! Made a few comments about inconsistencies in code style. Another thing I found strange was structs inheriting from classes, with the UI element. I think we want to keep them all classes, and that implies more encapsulation as well, that currently isnt in the structs (for button for example).

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/private/ui_text.cpp
> +            const auto& character = font->characters.at(i);
unclear type

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/private/viewport.cpp
> +    for (const auto& i : _baseElements)
variable name

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/private/viewport.cpp
> +    for (const auto& i : _baseElements)
variable name

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/ui_button.hpp
> +struct UIButton : public UIElement
structs are inheriting from classes seems strange, i would keep it classes

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/ui_element.hpp
> +    virtual void Update(const InputManager& input)
why are these definitions defined in the header file? They can be moved to the source file right

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/ui_element.hpp
> +    UIElement* AddChild(std::unique_ptr<UIElement> child)
Sharing the backing pointers of unique ptrs, sounds contradicting, shouldnt we just use shared_ptr?

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/ui_element.hpp
> +    UIElement* AddChild(std::unique_ptr<UIElement> child)
or references if they wont be kept around

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/ui_element.hpp
> +        if (_children.size() < _maxChildren && child != nullptr)
unclear why there is max child count? isn't it just a vector backing this?

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/ui_module.hpp
> +    std::unique_ptr<Viewport> viewport;
should this be public?

2024-12-02 15:20 UTC, MuskettaMan commented on engine/user_interface/public/viewport.hpp
> +    glm::vec2 extend;
these should be private with getters

2024-12-02 16:05 UTC, luuk234 commented on engine/CMakeLists.txt
> +target_add_module(Engine user_interface UserInterface)
this is the folder name

2024-12-02 16:06 UTC, luuk234 commented on engine/CMakeLists.txt
> +target_add_module(Engine user_interface UserInterface)
I assume we use the same naming convention for folders as files?

2024-12-02 16:14 UTC, luuk234 commented on engine/renderer/private/gpu_resources.cpp
> +    if (data == nullptr)
clang tidy does but have we ever made a formal decision on this? i see if in a lot of other places in the codebase

2024-12-04 09:45 UTC, luuk234 commented on engine/renderer/public/renderer.hpp
> +    Viewport& _viewport;
I would prefer clear ownership.

2024-12-05 11:43 UTC, MuskettaMan approved these changes

2024-12-05 15:06 UTC, merged